### ISSUE TITLE
Adding a feature to change the email.

### ISSUE THREAD

**Issue by ihu57** [Stremio/stremio-features#576] opened 2023-11-08 17:15 UTC
Hi,
I think stremio need to add a feature to change the email.

Last time I have deleted my email and right now i can reach the account, but I can't change anything like password or something else without my old email.

So I think adding this feature will be a great thing.

Also if I can transfer my data from account to another account that will be a good idea.

**Comment by TRtomasz** [comment] 2023-11-08 21:33
duplicate of https://github.com/Stremio/stremio-features/issues/148

**Closed by TRtomasz** 2023-11-08 21:33 UTC
