### ISSUE TITLE
[Feature Request] Organize Main Page and Change Order of Catalogs 

### ISSUE THREAD

**Issue by icpryde** [Stremio/stremio-features#551] opened 2023-10-13 16:41 UTC
I really would love the ability to turn on/off certain catalogs and also reorganize the order they appear as well, example is with Trakt. I just want it to show watchlist and collection but it also shows history, recommendations and a few others and I would like to keep it minimal.

Thank you for all your hard work.

**Comment by tundrablasen** [comment] 2023-10-15 16:56
Reorganising of Home Screen and the widget lists is really needed

**Comment by bennodxb** [comment] 2023-10-15 17:26
This seems like its an essential feature. I spent ages trying to work out why I couldnt find the option.

**Comment by mophawka** [comment] 2023-10-15 18:40
100% +1

**Comment by TuupacFR** [comment] 2023-10-28 08:03
+1, let us re order the homepage !

**Comment by Zizou3000** [comment] 2023-11-05 16:08
We really need this...

**Comment by lothar-cell** [comment] 2024-01-07 08:53
+1

**Comment by rawIce** [comment] 2024-03-23 22:22
+1 

Really needed, including the option to hide or at least move the default Cinemata catalogs
There are also several threads and comments on Reddit regarding this functionality.

**Comment by lothar-cell** [comment] 2024-03-23 22:38
Here's an unofficial workaround, until they come to their senses finally: https://addon-manager.dontwanttos.top

**Comment by bennodxb** [comment] 2024-03-24 07:07
Why did you delete the previous reply? You should incorporate this functionality into your app, not try to censor it. It makes stremio so much better.

**Comment by lothar-cell** [comment] 2024-03-24 07:29
https://github.com/Stremio/stremio-features/issues/562#issuecomment-1969170326

**Comment by TRtomasz** [comment] 2024-03-24 14:11
closing as a duplicate

**Closed by TRtomasz** 2024-03-24 14:11 UTC

**Comment by lothar-cell** [comment] 2024-03-24 15:20
More will come:D

**Comment by mophawka** [comment] 2024-03-24 18:46
> closing as a duplicate

odd. since the other is a duplicate of this. not the other way around.
