### ISSUE TITLE
Stremio background playback feature

### ISSUE THREAD

**Issue by Maremelows** [Stremio/stremio-features#548] opened 2023-10-13 13:20 UTC
I would like Stremio to have Background playback like Youtube, so that we can watch the content we are going to watch at the same time while doing something else with the phone.

**Comment by TRtomasz** [comment] 2023-10-16 12:28
closing as duplicate of multiple picture in picture previous requests

**Closed by TRtomasz** 2023-10-16 12:28 UTC

**Comment by RokeJulianLockhart** [comment] 2024-09-09 00:14
https://github.com/Stremio/stremio-features/issues/471#issue-1877275203
