### ISSUE TITLE
Include Option to "Download Content" in mobile and Android TV versions off Stremio

### ISSUE THREAD

**Issue by luizthiagor** [Stremio/stremio-features#619] opened 2023-12-11 19:18 UTC
**Is your feature request related to a problem? Please describe.**

Dont have option to download a movie or Serie Episode in mobile and in Android TV versions 

**Describe the solution you'd like**

Create a button to "download" the content like has in PC version

**Describe alternatives you've considered**
Create button to download the content using other apps if not possible to create "in App" function

**Additional context**

Is only to download Contents in app like PC version have ...if have it, i can watch without internet connection.

The option can give function to save file in device and/or to save in library and watch later

**Comment by TRtomasz** [comment] 2023-12-11 22:34
closing as a duplicate of many others feature requests.

**Closed by TRtomasz** 2023-12-11 22:34 UTC
