### ISSUE TITLE
Two suggestions

### ISSUE THREAD

**Issue by acamposxp** [Stremio/stremio-features#588] opened 2023-11-17 19:17 UTC
Two suggestions to make the Stremio almost perfect (in my opinion):
1. Allow the order of the catalogs to be customized (regardless of whether the add-ons were installed before or after);
2. Synopses and titles in the user's language as in Kodi (in tmdb: https://www.themoviedb.org/search?language=pt-BR&query=?)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TRtomasz** [comment] 2024-06-06 15:44
Closing as a duplicate of other issues requesting the same. Please remember use one issue per one feature request.

**Closed by TRtomasz** 2024-06-06 15:44 UTC
