### ISSUE TITLE
Allow multiple accounts (not users) per app 

### ISSUE THREAD

**Issue by cerels** [Stremio/stremio-features#1029] opened 2024-10-10 16:59 UTC
Stremio Version
Android TV

Is your feature request related to a problem? Please describe.
Yes, the current Stremio app only allows logging in with a single account per app session. This limitation makes it inconvenient for users who manage multiple accounts (e.g., personal, work, or different household accounts). Switching between them requires constantly logging out and back in, which is time-consuming.

Describe the solution you'd like
I'd like the app to support logging in with multiple accounts at once (not just multiple profiles within one account). This way, I could switch between them seamlessly without logging out. This feature would be especially helpful when managing different households or content preferences from the same device. From my perspective, this seems easier to implement than full multi-user support, as it simply involves toggling between authenticated accounts.

Describe alternatives you've considered
The alternative would be full multi-user support, where each user has their own independent session. However, implementing multiple accounts per app might be a simpler solution to address a large part of the issue, as it avoids the need for developing and managing user-specific profiles while still providing flexibility.

Additional context
This feature is especially relevant for households where different users may have different content preferences or Stremio setups. Being able to quickly switch accounts would make it more convenient to access each person’s settings or add-ons without constant logouts.

**Comment by TRtomasz** [comment] 2024-10-11 12:09
closing as duplicate, there are already many issues like that one open

**Closed as completed by TRtomasz** 2024-10-11 12:09 UTC

**Comment by cerels** [comment] 2024-12-21 16:01
> closing as duplicate, there are already many issues like that one open

Not really @TRtomasz all other posts I have seen are about having multiple profiles on one account, my suggestion is being able to log on to different separate accounts within the app just like how you can have many accounts on your Facebook app, I reckon this would be easier to implement and is more modular than having your profiles linked to an account

**Comment by MullyCap2004** [comment] 2024-12-27 01:47
I need this.

**Comment by NeurekaSoftware** [comment] 2025-08-22 01:19
This is definitely not a duplicate of #622. The requests are for different things. Allowing multiple accounts is more ideal than multiple users under the same account IMO.
