### ISSUE TITLE
More info in mobile player

### ISSUE THREAD

**Issue by Flolon** [Stremio/stremio-features#457] opened 2023-08-30 20:03 UTC
**Is your feature request related to a problem? Please describe.**
I get frustrated when I can't tell how much of a stream is buffered.

**Describe the solution you'd like**
I'd like to see the same information I can see in the desktop/web app. This includes the speed of the buffering, % of the stream buffered, and even the connected peers would be nice to have.

**Describe alternatives you've considered**
Something similar YouTube player where you can see how much of the stream/video is buffered visually. But at the very least, an overlay you can toggle/bring up with the information, like on the desktop app.

**Additional context**
![image](https://github.com/Stremio/stremio-features/assets/15746034/39c03516-f832-4d22-963a-f666e359171e)
*the overlay as seen in the desktop app*

**Comment by TRtomasz** [comment] 2023-09-04 09:09
duplicate of https://github.com/Stremio/stremio-features/issues/457

**Closed by TRtomasz** 2023-09-04 09:09 UTC

**Comment by Flolon** [comment] 2023-09-04 11:44
Duplicate of? This *is* 457 🤔
