### ISSUE TITLE
Actor/Director info Android TV

### ISSUE THREAD

**Issue by Maddhatter182** [Stremio/stremio-features#398] opened 2023-06-27 22:31 UTC
i've been waiting for years for this feature. i want the director/actor feature where i can look up the actor director or writer and see the movies they made or at least when im hovering over a movie i can see the director, and not having to go to google every single time.

**Comment by TRtomasz** [comment] 2023-06-29 08:37
closing as duplicate of https://github.com/Stremio/stremio-features/issues/302
btw "for years"? We released Android TV app like a year ago lol.

**Closed by TRtomasz** 2023-06-29 08:37 UTC
