### ISSUE TITLE
multi subtites

### ISSUE THREAD

**Issue by jihadismail8** [Stremio/stremio-features#508] opened 2023-09-19 09:47 UTC
Multi subtites at the same time , i think this feature has been requested before , but i do not understand why it has been rejected .  i found some open source solutions for the feature . 
 that can help with the requested feature , https://github.com/wistful/srtmerge , you can easily add a button that would merge two or more srt files (or links) and use it in the vedio . here is a Rust package https://github.com/emk/subtitles-rs

**Comment by TRtomasz** [comment] 2023-09-19 10:09
duplicate of https://github.com/Stremio/stremio-features/issues/372

**Closed by TRtomasz** 2023-09-19 10:09 UTC
