### ISSUE TITLE
Subtitle Positioning

### ISSUE THREAD

**Issue by imurreflection** [Stremio/stremio-features#122] opened 2020-01-07 08:59 UTC
Can I request developers to add subtitle positioning as a feature in this great application. Right now they come quite up while watching and it kills the viewing experience. We can have something like above the video, below the video or bottom of the video or in form of 0, 10,20,30 etc.

**Comment by Ivshti** [comment] 2020-01-11 19:23
thanks for the feedback; I'll close this as a duplicate of #102, #68 , but considering that there are plenty of requests for this already, we'll consider implementing

**Closed by Ivshti** 2020-01-11 19:23 UTC

**Comment by imurreflection** [comment] 2020-01-28 06:04
Dear Ivshti, could you please let us know tentative implementation time for thus feature. Initial request was raised three years back.

**Comment by rustynail4** [comment] 2020-11-20 00:07
Please, please implement this feature ASAP! 
It´s literally the only thing still keeping me on Kodi (and I believe I´m speaking for many other users).

**Comment by Sunnysky** [comment] 2020-11-20 18:49
Raise your TV so you can see it above your feet

Regards,
Tony
