### ISSUE TITLE
Skip series intro

### ISSUE THREAD

**Issue by PixelQubits** [Stremio/stremio-features#653] opened 2023-12-27 02:52 UTC
A feature similar to sponsorblock would be interesting to skip the opening of TV series, that is, users would be in charge of marking where the opening ends.

**Comment by TRtomasz** [comment] 2023-12-27 23:01
duplicate of other issues, please use search feature before creating a new one it will help us maintain this repo.

**Closed by TRtomasz** 2023-12-27 23:01 UTC
