### ISSUE TITLE
Add addon settings

### ISSUE THREAD

**Issue by crstestacc** [Stremio/stremio-features#106] opened 2019-04-30 06:30 UTC
If we write addon that based on service and this service req. authentication we need to enter our user/pass etc. So if we can get even basic settings for addon that will be great!

**Comment by Ivshti** [comment] 2019-04-30 09:08
duplicate of https://github.com/Stremio/stremio-addon-sdk/issues/17

**Closed by Ivshti** 2019-04-30 09:08 UTC
