### ISSUE TITLE
Synopses translations

### ISSUE THREAD

**Issue by hassansaadfr** [Stremio/stremio-features#394] opened 2023-06-10 15:07 UTC
**Is your feature request related to a problem? Please describe.**
Synopses are not translated or fetched in the correct language despite the configuration

**Describe the solution you'd like**
Fetch synopses in UI language

**Comment by TRtomasz** [comment] 2023-06-29 07:06
closing as duplicate of https://github.com/Stremio/stremio-features/issues/236

**Closed by TRtomasz** 2023-06-29 07:06 UTC

**Comment by gonsodany** [comment] 2024-04-05 12:54
except its not "completed", its been almost a year and synopses are still fetched in english only
