### ISSUE TITLE
If you pause video stream on Android TV, and then unpause it, you lose relatively large portion of audio/dialogue

### ISSUE THREAD

**Issue by jan-kleks** [Stremio/stremio-features#549] opened 2023-10-13 16:19 UTC
**Is your feature request related to a problem? Please describe.**
In other streaming apps on my Android TV device, if I pause the video, and then unpause it, I lose maybe half a syllable of speech. However, in the case of Stremio, it is often such a large portion of dialogue that I have to rewind the movie to hear what has actually been said.

I have also tested this in Stremio on a Linux desktop, and even with a much slower Internet connection, the problem is simply not present there (caching on and off).

**Describe the solution you'd like**
Improved audio/video synchronization when unpausing

**Additional context**
Android TV 11, Nvidia SHIELD TV connected to an AV receiver, 100 Mbps+ Internet connection. Using default Stremio player. Also tested with tunneled playback and libvlc.

**Comment by jan-kleks** [comment] 2023-10-29 22:21
I will just add that I have now installed the mpv-android as an external player on my Nvidia SHIELD. An the problem is not present there.

**Comment by jan-kleks** [comment] 2023-11-01 01:41
Probably related issues: https://github.com/Stremio/stremio-core/issues/550

**Comment by TRtomasz** [comment] 2024-06-06 15:17
cant reproduce the issue, perhaps it was fixed with media3 update.

**Closed as completed by TRtomasz** 2024-06-06 15:17 UTC
