### ISSUE TITLE
Change metadata language on Cinemata

### ISSUE THREAD

**Issue by Arbitrate3280** [Stremio/stremio-features#360] opened 2023-02-04 15:21 UTC
Right now Cinemata only shows metadata in english. A way to work around it is to download the TMDB addon and set the metadata language to your desired one. But unfortunately you can't hide data from Cinemata and it always shows up first in both the desktop app and the android tv one.

If changing metadata for Cinemata is not possible maybe allowing us to change the display order so the TMDB addon content shows up first would also be an acceptable solution.

**Comment by YuriAniceto** [comment] 2023-08-28 13:51
Please, this would be really important for me, and shouldn't be hard on IMDB api to change language, or let TMDB handle metadata for all sections.

**Comment by r4f4w** [comment] 2023-10-30 16:39
+1 on this matter. I can't believe that, of all the things Stremio can do, this is not one of them. This is such a simple core feature that should have been implemented many years ago. Additionally, if they don't want to pursue this issue, they should at least give us a chance to change to TMDB as the default metadata provider or have it appear first on the homepage and in searches.

**Comment by MalcolmBrt** [comment] 2024-02-20 06:58
I also think it could be a good feature to implement. Not everyone speaks fluent English, the proof is I have to use google translate to write this.

**Comment by TRtomasz** [comment] 2024-06-06 14:54
closing as duplicate of https://github.com/Stremio/stremio-features/issues/236

**Closed by TRtomasz** 2024-06-06 14:54 UTC
