### ISSUE TITLE
Feature: Ability to hide watched videos from Discover

### ISSUE THREAD

**Issue by kiarfuzzy** [Stremio/stremio-features#156] opened 2020-10-10 17:32 UTC
Often i try to find a new movie i didn't watched in Discover, but it's a tedious job because every time i need to "dig" trough a lot of things i already watched until i find something new. An option / button to hide watched items would be awesome.

**Comment by TRtomasz** [comment] 2020-10-10 22:37
Duplicate of https://github.com/Stremio/stremio-features/issues/96

**Closed by TRtomasz** 2020-10-10 22:37 UTC
