### ISSUE TITLE
Option to Disable/Enable network status notifications

### ISSUE THREAD

**Issue by CrisBarrientos** [Stremio/stremio-features#742] opened 2024-02-27 16:47 UTC
**Stremio Version**
Stremio Version 4.4.165 WINDOWS 10 - DESKTOP APP

Sometimes the internet provider is full of micro-cuts in service for long periods of time, which makes Stremio pop messages relating to network status connection ("you are currently offline" or "you are back online now") show up endlessly in pairs at the same time, which is very annoying, since every pop window has to be manually closed or wait to disappear for several seconds, ruining the movie experience, even when the the movie plays seamless during this cuts, beacause the cuts are super short but persistent.

Should be an option to disable this particular kind of notification permanently, or enable if needed.

**Comment by bobdanek** [comment] 2024-03-02 02:36
Probably a duplicate of https://github.com/Stremio/stremio-shell/issues/337

**Comment by CrisBarrientos** [comment] 2024-03-02 12:17
It is, thank you, I added a possible solución to that thread. 👍🏻

**Comment by core1024** [comment] 2024-03-06 13:10
This feature is now implemented. Will be available in the next release.

**Closed as completed by core1024** 2024-03-06 13:10 UTC
