### ISSUE TITLE
Request: add option "close window to close app"

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Stremio/stremio-features#129] opened 2019-06-14 07:12 UTC
Instead of sending it to the tray.
To sent to the tray, add option to click on the tray icon.

Currently it's very annoying to right click on the tray and then choose to exit, just to exit the app.
Even ALT+F4 doesn't really exit it.

I'm using Stremio 4.4 on Windows 10, BTW.
It didn't occur on previous versions.

**Comment by victorgveloso** [comment] 2021-02-16 22:15
Duplicate of #71

**Comment by AndroidDeveloperLB** [comment] 2021-02-16 22:49
@victorgveloso The other one is for Linux. Here it's for Windows.
Can you please update there that it's for Windows too?

**Comment by victorgveloso** [comment] 2021-02-16 23:12
I've already mentioned this issue there and requested for the title modification.

**Comment by AndroidDeveloperLB** [comment] 2021-02-16 23:32
@victorgveloso Sorry I don't see this.
All I see is "Duplicate of #71"

**Comment by victorgveloso** [comment] 2021-02-16 23:58
Look at the last comment of the aforementioned Issue: https://github.com/Stremio/stremio-features/issues/71#issuecomment-780155202

**Comment by AndroidDeveloperLB** [comment] 2021-02-17 00:08
@victorgveloso Oh ok.

**Closed** 2021-04-20 10:16 UTC
