### ISSUE TITLE
Change tray icon

### ISSUE THREAD

**Issue by maxoku** [Stremio/stremio-features#220] opened 2021-11-28 18:29 UTC
**Is your feature request related to a problem? Please describe.**
Tray icon when hidden goes to menu with white background and while the icon itself is completely white is invisible there. There's also no tooltip to know what is that icon.

**Describe the solution you'd like**
Change the tray icon e.g. to other color. Additionally add a tooltip too.

**Describe alternatives you've considered**
Allow to choose a different icon or color by any means.

**Additional context**
Here you can see that icon is invisible and there is no tooltip on mouse hover:
![image](https://user-images.githubusercontent.com/17256400/143780995-48ceea4f-a853-4a7a-b562-19e1d57ac2a5.png)

Here it's how the icon gets visible when I try to move it:
![image](https://user-images.githubusercontent.com/17256400/143781016-4cad7470-0413-4596-a64b-6ca6b7ad5e79.png)

**Comment by TRtomasz** [comment] 2022-01-05 13:23
So if we change tray icon colour to lets say green, then it will not be visible when someone set it to green colour? 
Could you tell me what windows version is this? I cant reproduce it on my system.

**Comment by maxoku** [comment] 2022-01-05 14:57
It's Windows 8.1 and I don't really see an option to change that color.
Discord icon's color is white, but it has black contours, so it's visible on white background.

**Comment by TRtomasz** [comment] 2024-06-04 14:30
closing as windows 8.1 is now not supported

**Closed by TRtomasz** 2024-06-04 14:30 UTC
