### ISSUE TITLE
tvshow time integration

### ISSUE THREAD

**Issue by gabrielbiel7** [Stremio/stremio-features#81] opened 2018-01-31 00:26 UTC
when we finish episodes in stremio app, it could automatically mark as watched in tvshow time. this feature already exists in popcorn time. thanks

**Comment by Skywalkr08** [comment] 2018-05-28 19:15
I was here thinking of posting it myself. There should be an option for TV Time scrobbling instead on Trakt

**Comment by MootMootz** [comment] 2018-06-11 22:29
Hello there,

I expected this feature to be added so many times wondering it would have been done before I make a search on Google... :/
Sooooo... please guys, go for it.
It'd be very nice to be organized... ;)

(I assume you would be helpful for a LOT of people)

**Comment by TRtomasz** [comment] 2022-09-07 13:31
closing as duplicate of https://github.com/Stremio/stremio-features/issues/21

**Closed by TRtomasz** 2022-09-07 13:31 UTC
