### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by Roedosla** [Stremio/stremio-features#378] opened 2023-05-08 17:06 UTC
Hello. Do you think it's possible to add a function that allows to view offline the content? Specially in smartphone version. In this way, you could download the content with a WiFi network and then watch it when the network connection is unstable, even in airplane mode, for example when traveling on a bus or train or airplane. This function would be great.

**Comment by TRtomasz** [comment] 2023-05-15 08:08
Please do not clear the form whem creating an issue.
Closing as duplicate of https://github.com/Stremio/stremio-features/issues/281

**Closed by TRtomasz** 2023-05-15 08:08 UTC
