### ISSUE TITLE
Allow quit instead of close to system tray on Linux.

### ISSUE THREAD

**Issue by gapplef** [Stremio/stremio-features#71] opened 2017-10-20 13:03 UTC
Current close Stremio wouldn't really quit the application, and will stay in the system tray. People need to right click on the system tray icons to quit.
But after Gnome 3.26, the system tray was removed, and once Stremio was closed, people couldn't see it in anywhere, but it's still running in the background.
To quit the application people need to kill the process with system monitor.
So, Please add an options to quit the application when click the close button.

**Comment by Ivshti** [comment] 2017-10-22 13:42
Alternatively, we can make a notification "Stremio is still running", what do you think about that?

**Comment by gapplef** [comment] 2017-10-22 14:13
A notification will let people know Stremio is still running, but still have no way to quit the application.
People still need to kill the process with system monitor in order to quit.

**Comment by root-phantasoft** [comment] 2020-01-28 01:50
Bump. 2020, this is still not fixed.

**Comment by nemanjan00** [comment] 2020-02-08 17:25
There is no way for me to close stremio, while using Sway WM

I have to kill it from htop every time...

**Comment by sandorex** [comment] 2020-05-27 22:34
I have to run `killall stremio` to kill it every time cause i do not have a sys tray

**Comment by Sunnysky** [comment] 2020-05-28 16:04
Why does stremio cause bloated Powershell activity ? Yet no Negative effect when killed

Regards,
Tony

**Comment by Sunnysky** [comment] 2020-06-09 02:48
I often see 1 or more powershell.exe 's running at full speed 12.5% for 
an 8 core i7 each, taking needless CPU power.

which may be terminated.

**Comment by Ivshti** [comment] 2020-06-09 06:45
because of this addon https://github.com/stremio/stremio-local-addon

which may be disabled with the instructions here https://www.reddit.com/r/Stremio/comments/gxocz5/protected_addon_local_files/

**Comment by vinhphamh** [comment] 2020-09-07 02:49
Same problem in Windows 10.   I'd like a faster way to quit Stremio completely instead of having to go to the system tray to quit.  Thanks.

**Comment by victorgveloso** [comment] 2021-02-16 22:20
This shouldn't be exclusive to Linux. As @vinhphamh has already mentioned windows users are interested in that feature as well. Another example is the Issue #129 that asks for the same feature but on windows.
Please, I suggest you to change the issue title to "Allow quit instead of close to system tray", as Gnome bug is an aggravating to a more general feature.

**Comment by AndroidDeveloperLB** [comment] 2021-04-20 10:21
Was this closed as the feature was added?
Or even better: close by default will really close the app?

**Comment by TRtomasz** [comment] 2021-04-20 11:44
You can find this option in the settings now 
![image](https://user-images.githubusercontent.com/40594253/115390450-29207b80-a1d6-11eb-8581-49070b1ac54c.png)

**Comment by AndroidDeveloperLB** [comment] 2021-04-20 16:14
@TRtomasz Hm I don't see it on your screenshot and on my Stremio app. 
I have v4.4.135.

**Comment by victorgveloso** [comment] 2021-04-20 19:44
> Hm I don't see it on your screenshot and on my Stremio app.

I think you're misinterpreting @TRtomasz's screenshot. He/She is highlighting the quit button added to the config page.

IMO the problem with that solution relates to the @vinhphamh's comment: 

> Same problem in Windows 10. I'd like a faster way to quit Stremio completely instead of having to go to the system tray to quit. Thanks.

The problem with "close to tray" is the time spent. The implemented solution still require more than one click (1st click on config three-dots button; 2nd select config menu; 3rd press QUIT button). That's the same amount of clicks required before (1st click on X for closing to tray; 2nd right-click on tray icon; 3rd select quit option).

> You can find this option in the settings now

That's not an actual **option** in settings, but a button to quit in settings. We were expecting a checkbox (just like the one used for the option "Escape key exit full screen"). This checkbox could be labeled "close to system tray on exit", be enabled by default, and changing the close button behavior when it is disabled.

**Comment by AndroidDeveloperLB** [comment] 2021-04-20 20:01
@victorgveloso So why close the issue?
I requested to be able to close the app by simply pressing the X button of its window, instead of minimizing to the system tray.
And it was marked as a duplicate to here, and then here it got closed, and I don't see it anywhere...

**Comment by victorgveloso** [comment] 2021-04-20 20:07
Hold on maybe I was not clear enough, but I'm on your side. 

I support the opinion that the things are not done yet and this issue should be reopened.

I don't have permission to reopen tho... We need to wait @gapplef or @TRtomasz reopen it for us.

**Comment by gapplef** [comment] 2021-04-21 10:27
@victorgveloso I agree with your comments, but I also have no permission to reopen the issue.

**Comment by jaruba** [comment] 2021-04-21 11:12
![AdventurousPointlessGull-size_restricted](https://user-images.githubusercontent.com/1777923/115544681-92be8980-a2ab-11eb-977e-def03696a2cb.gif)

**Comment by jaruba** [comment] 2021-04-23 16:02
![Screen Shot 2021-04-23 at 18 56 05](https://user-images.githubusercontent.com/1777923/115898271-099f8200-a466-11eb-9eb3-4047c5c27c7e.jpg)


![its_happening](https://user-images.githubusercontent.com/1777923/115898474-44a1b580-a466-11eb-9de0-f50631cae1b8.gif)

_will be available in the next Stremio Desktop release, which should start rolling out next week, @TRtomasz should be thanked for implementing it_

**Comment by AndroidDeveloperLB** [comment] 2021-04-23 20:37
@jaruba Please don't close this till it's really added.
Also, will it be turned on by default?

**Comment by jaruba** [comment] 2021-04-23 20:40
@AndroidDeveloperLB you're pushing ur luck 🤣

**Comment by AndroidDeveloperLB** [comment] 2021-04-23 20:59
@jaruba 
When I choose to close an app, I expect it to close. Not to minimize somewhere. For this I can have a setting if I want it working differently. Some apps even offer a 4th button to minimize to the system tray.
Not to mention when it's a player-app.
Please reconsider this. Why not follow the logic of all other apps?

**Comment by jaruba** [comment] 2021-04-23 21:14
@AndroidDeveloperLB 

> I expect it to close

It will close, chill..

> Why not follow the logic of almost all other apps?

We will not change the default behaviour of the app that has been this way for the last 7 years. A setting has been added that will make it always close when you click the "X" window button, I would presume this is satisfactory to your needs..

**Comment by AndroidDeveloperLB** [comment] 2021-04-23 21:21
@jaruba It does. Just expect it to behave nicely like the rest of the apps.
Not against the OS.
Anyway, thank you for adding this.

**Comment by victorgveloso** [comment] 2021-04-23 21:31
> @jaruba 
> When I choose to close an app, I expect it to close. Not to minimize somewhere. For this I can have a setting if I want it working differently. Some apps even offer a 4th button to minimize to the system tray.
> Not to mention when it's a player-app.
> Please reconsider this. Why not follow the logic of **almost** all other apps?

uTorrent works similarly and steam... Just to name a few. Why do you want to change the experience from other users that are satisfied?

**Comment by jaruba** [comment] 2021-04-23 21:31
@AndroidDeveloperLB

Stremio uses very little resources while it stays as a background app, it does not download / upload, it's just there.

Now keep in mind that this is an app with over 15 million users, of which, extremely few ever considered it staying in the tray as an issue.

From these users, most prefer it to start instantly (as it is already running) as opposed to closing it completely.

This request is for a power user setting, which I personally consider satisfied by adding a setting for it.. (as was explicitly requested within this issue thread)

Please keep in mind that what is best for you, is not necessarily best for 15 million other people..

**Comment by AndroidDeveloperLB** [comment] 2021-04-23 21:39
@victorgveloso uTorrent isn't a player app.
Same for steam.
You should take an example of player apps. 
Example is "Media Player classic", "BsPlayer", and even of MS-Windows itself.
Another good comparison would be with other video streaming apps, such as Popcorn time.
For every example you find that apps minimize to tray by default, I can find 10 that it's not (and probably more similar, too).

@jaruba So if it doesn't do anything, why stay at all? What's the purpose of having it in the system tray? Imagine that all apps would be this way. Eventually you will have tens of icons of all apps you have, just for opening them, even tough you already have shortcuts to them already.
As for number of complaints compared to users, most users don't even know about this website, let alone think of writing here.

As for "what's best", what's wrong with asking the user what's best?
You can add Analytics to what is chosen by the dialog I've suggested, and see what people really prefer instead of guessing.

BTW, you guys say that if it was as such for years, it doesn't make sense to change. 
You could instead just set it to close by default for new users, instead of existing ones. For existing ones the setting will be saved to minimize to tray. New users are used to how it works on other apps instead.

**Comment by jaruba** [comment] 2021-04-23 21:54
@AndroidDeveloperLB

> So if it doesn't do anything, why stay at all?

I already explained one of the benefits:

> From these users, most prefer it to start instantly (as it is already running) as opposed to closing it completely.

**Closed by jaruba** 2021-04-23 21:54 UTC

**Comment by AndroidDeveloperLB** [comment] 2021-04-23 21:58
@jaruba OK so please, for new users who didn't use it before, ask them what they prefer. 
Have a dialog to ask what to do, with a checkbox to remember the selection.
This way you could know how many users prefer to close, and how many prefer to minimize to tray.

> For the same reason that a "quit" button in the settings was not enough, number of clicks and expected behaviour.. it's bad UX..

The bad UX that requires multiple clicks here isn't a single dialog. It's the one that forces you to have it minimized to the tray, and then you need more clicks than this dialog (right click and then close, every time you close the app).

**Comment by AndroidDeveloperLB** [comment] 2021-04-23 22:00
@jaruba OK. Can you please, then, have Analtyics on how many enable the checkbox in the settings?
Then you could analyze how many have it this way.

**Comment by steviator** [comment] 2023-08-06 02:39
It's outrageous to suggest that because very few Stremio users have reported this as an issue on Github, that they aren't bothered by it. A number of things need to happen before people complain here.

1) They have to know that it keeps running in the background, which is not a given, considering that the icon hides itself on Windows, and there isn't any system tray on Gnome at all.

2) They have to assume that the developers would be willing to change this obviously intentional behavior

3) They have to know that Stremio has a Github page

4) They have to assume that this non-bug will be accepted as an issue on Github

5) They have to have a Github account, or be willing, and prepared to expend the effort to create an account on Github, a Microsoft owned website that requires you to surrender personal details including their email address.

6) They need to be bothered actually reporting it, and able to articulate, in English, what the problem is.

On Gnome, in particular, exiting on close should be the default as there is literally no hint that the application doesn't exit when its main window disappears. 

I personally consider Gnome's lack of a system tray to be idiotic, but as long as Gnome continues to be the default desktop on the most commonly used Linux distributions, this will be an issue for Linux novices, and not just power-users.

**Comment by victorgveloso** [comment] 2023-08-06 05:00
![image](https://github.com/Stremio/stremio-features/assets/11022419/4cc184b6-fd03-4086-b281-62f521f00f42)

**Comment by victorgveloso** [comment] 2023-08-06 05:13
> On Gnome, in particular, exiting on close should be the default
That is a different issue, this issue is to "Allow quit instead of close to system tray on Linux"

And do not bother to file an issue because the dev team already expressed no intention to change the default settings. After all, it will impact existing users and consistency is key.
 
 > there is literally no hint that the application doesn't exit when its main window disappears.

There is literally an option in the settings to turn this behaviour off. Isn't that a good hint?

> I personally consider Gnome's lack of a system tray to be idiotic

Chill out mate, both Stremio and Gnome are open-source non-profit products built from voluntary contributions and some paid devs. You either contribute to those projects, create an alternative, or provide constructive feedback. You won't get anywhere with such an attitude.
